#!/usr/bin/env bash
#printing the files in the directory

for file in *
do
  if [[ $file != .* ]]
  then
    if [[ $file == *"-"* ]]
    then
      echo "${file#*-}"
    else
      echo "$file"
    fi
  fi
done
