#!/usr/bin/env bash
# A script to use nginx user to run nginx
sudo sed -i "s/user www-data/user nginx/g" /etc/nginx/nginx.conf
sudo sed -i "s/listen 80 default_server;/listen 8080 default_server;/g" /etc/nginx/sites-enabled/default
sudo -u nginx service nginx restart
