#!/usr/bin/env bash
# A script to use nginx user to run nginx
sudo sed -i "s/user www-data/user nginx/g" /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/g" /etc/nginx/sites-enabled/default
sudo service nginx restart
