#!/usr/bin/env bash
# A script to use nginx user to run nginx
sudo service nginx stop
sudo userdel nginx
sudo useradd -r -s /bin/false nginx
sudo sed -i "s/user www-data/user nginx/g" /etc/nginx/nginx.conf
sudo sed -i "s/listen 80/listen 8080/g" /etc/nginx/sites-enabled/default
sudo service nginx start
